# -*- coding: utf-8 -*-
"""Python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwzjyobuspY6FZdTJEbW85BrszWwIQYP
"""

a=9

print(type(a))

string1="Hi"
string2="hello"
string3="hhh"
print(string1+string2+string3)

a=2
b=45
c=89
print(a+b-c)

l=[1,34,56,"h","f","u"]
l[1]=88
l[2]=10
print(l)

svc=64
eg=36
pp=54
ep=88
uhv=88
total=(svc+eg+pp+ep+uhv)
per=(total*100)/500
print(per)

principle=10000
time=10
rate=12
intrest=(principle*time*rate)/100
print(intrest)



p=1000
r=8
n=11
t=2
u=pow((1+r/n),(t*n))
c=p*(u-1)
print(c)

base=10
height=15
area=0.5*10*15
print(area)

radius=7
area=(22*radius*radius)/7
print(area)

print("NAME=Udayraj Ghorpade")
print("AGE=18")
print("COLLEGE=JNEC")
print("BRANCH=CSE")
print("SUBJECT=PP,EG,SVC,EP,UHV")
print("HEIGHT=6ft")

a=1
d=2
t1=a+(1-1)*d
t2=a+(2-1)*d
t3=a+(3-1)*d
t4=a+(4-1)*d
t5=a+(5-1)*d
print(t1)
print(t2)
print(t3)
print(t4)
print(t5)

a=5
b=7000
c=b//a
print(c)

website="apple.com"
print(website)
#assine new 
website=("laptop.com")
print(website)

#Python program to
#demonstrate numeric value
a=5
print("Type of a:",type(a))
b=0.5
print("\nType of b:",type(b))
c=2+7j
print("\nType of c:",type(c))

str1='hello java point'
str2=' how are you'
print(str1[0:2])
print(str1[4])
print(str1*2)
print(str1+str2)

l=[1,"hi","python",2]
print(l[3:])
print(l[0:2])
print(l+l)
print(l*3)

t=("hi","python",2)
print(t[1:]);
print(t);
print(t+t);
print(t*3);
print(type(t))
#t[2]="Hi";



d={1:'jimmy',2:'alex',3:'john',4:'mike'};
print("1st name is "+d[1]);
print("2nd name is "+d[4]);
print(d);
print(d.keys());
print(d.values());

a=10
b=20
print(a/b)
print(a//b)
print(a%b)

a=0.7
b=7
d='u'
c=7+7j
print(type(a))
print(type(b))
print(type(d))
print(type(c))

s='welcome'
s1='hello'
print(s+s1)
print(s*4+s1*3)
print(s[0:3])
print(s+s1[0:2])
print(s1[4])
print(s[3])

x=float(input("Enter first value"))
y=float(input("Enter second value"))
z=x
x=y
y=z
print("x",x)
print("y",y)

str="hello"
print(str[0:3])

l=[1,"u",7,"d",22,"hello",0.5]
print(l)
print(l[0])
print(l[0:3])
print(l[5])
print(l+l)
print(l*2)
l[2]=777
print(l)

t=('hi','python',7,77)
print(t)
print(l+l)
print(type(t))
print(t[0:2])

dictionary

d={1:'Udayraj',2:'Eknath',3:'Ghorpade'}
print(d)
print(d[1])
print(d.keys())
print(d.values())

SETS

S=[7,77,777,7777]
S1=['hi','python',7,77,'welcome']
print(S)
print(S1)
S3=[1,2,33,4,3,5,55,5,77,77,88,2,88]
print(S3)

set={1,2,3}
print(set)
set={1.0,"Hello",(1,2,3)}
print(set)

In set all things can print as it is there is not any restriction.../..

set={1,0,7,5,6,7,6,5,5,3,3,1,1,8,8}
print(set)
print(type(set))

n=200
n2=101
sum=n+n2
print('sum of {0} and {1} is {2}'.format(n,n2,sum))
print('sum of {2} and {0} is {1}'.format(n,n2,sum))

n=12.45
n2=34.67
sum=(n+n2)
print('sum is %.2f'%sum)

rice=75*2
sugar=45*3
almond=400*1
cashew=600*3
sum=(rice+sugar+almond+cashew)
print("Total:-",sum)
print(sum)

a=print("Enter the amount of rice (75 RS/KG)")
a=int(input(print(a)))

b=print("Enter the amount of sugar (45 RS/KG)")
b=int(input(print(b))) 

c=print("Enter the amount of almond (400 RS/KG)")
c=int(input(print(c)))

d=print("Enter the amount  of cashew (600 RS/KG) ")
d=int(input(print(d)))

Total=(75*a)+(45*b)+(400*c)+(600*d)
print("Total",Total)

a=10
b=a
print(b)
b+=a
print(b)
b=-a
print(b)
b*=a
print(b)

x=10
y=12
print('x>y is ',x>y)
print('x<y is ',x<y)
print('x>=y is ',x>=y)
print('x<=y is ',x<=y)
print('x!=y is ',x!=y)
print('x==y is ',x==y)

x=True
y=False
print('x and y is ',x and y)
print('x and y is ',x or y)
print('x and y is ',not y)

print("Chhatrapati Shivaji Maharaj \n Chhatrapati Shahjiraje Bhosale \n Chhatrapati Malojiraje Bhosale")

a=77
b=7
c1=a>10
c2=b>10
print(c1 and c2)
print(c1 or c2)
print(not c1)
print(not c2)
print(type(c1))

x=500
y=1400
rate=x*y
b=0.15*rate
total=rate+b
print("Total Amount: ",total)

x=1500
y=4000
rate=x*y
tax=0.15
price=tax*rate
print("Total price of Plot is :-",price)

x=int(input())
n=int(input())
a=151*n
b=x-a
print("The total amount donated to 500 people is :-",a)
print("The total amount donate to NGO is :-",b)

print("Enter you SVC score out of 100")
svc=int(input())
print("Enter you EP score out of 100")
ep=int(input())
print("Enter you EG score out of 100")
eg=int(input())
print("Enter you PP score out of 100")
pp=int(input())
print("Enter you UHV score out of 100")
uhv=int(input())
sum=svc+ep+eg+pp+uhv
avg=sum/5
per=(sum/500)*100
print("Total Score out of 500: ",sum)

print("Average Score: ",avg)

print("Percentage: ",per)

x=10
y=20
z=x
x=y
y=z
print(x)
print(y)

n1=int(input())
n2=int(input())
print(n1+n2)
print(n2/n1)
print(n2-n1)
print(n2*n1)
print(n2%n1)

h=int(input("height of triangle="))
b=int(input("base 0f triangle="))
a=(0.5*b*h)
print("area of triamgle = ",a)

km=int(input("Distance between to cities in kilometers ="))
m=km*1000
cm=m*100
inchs=cm/2.5
feet=inchs/12

print("meter=",m)
print("centimeter=",cm)
print("inchs=",inchs)
print("feet=",feet)

#This is question number one of making calculator...
n1=int(input("Enter first number "))     
n2=int(input("Enter second number"))
sum=n1+n2
substraction=n1-n2
multiplication=n1*n2
division=n1/n2
print("sum of number is ",sum)
print(substraction)
print(multiplication)
print('division is %.2f'%division)

# area and perimeter of triangle
x=int(input("height of triangle "))
y=int(input("base of tringle "))
w=int(input("enter first side of triangle "))
u=int(input("enter second side of triangle"))
v=w+y+u
z=(1/2)*x*y
print("Area of triangle ",z)
print("Perimeter of triangle ",v)


# area and perimeter of square
a=int(input("Side of square is "))
b=a**2
c=4*a
print("Area of square is ",b)
print("Perimeter of square is ",c)

#Area and perimeter of rectangle
e=int(input("Length of rectangle is "))
f=int(input("Bredth of rectangle is "))
g=e*f
h=2*(e+f)
print("Area of Rectangle is ",g)
print("Perimeter of rectangle is ",h)

#Area and perimeter of circle 
i=int(input("Radius of circle is "))
j=2*3.14*i
k=3.14*i**2
print("Area of circle is ",k)
print("Circumference of circle is ",j)

#Distance between two cities 
a=int(input("Distance between two cities is (in km) "))

meter=a*1000 
print("Distance in meteris ",meter,"m")

feet=a*3280.84
print("Distance in feet is ",feet,"ft")

inches=a*39370.1
print("Distance in inches is ",inches,"inches")

centimeter=a*100000
print("Distance in centimeter is ",centimeter,"cm")

#Inter changing of two numbers
x=int(input("Enter first number "))
y=int(input("Enter second number"))
z=x
x=y
y=z
print(x,y)

#Temperature in centigrate to farhenheit
c=int(input("Temperature in centigrate is "))
f=1.8*c+32
print("Temperature in Farhenheit is ",f)

list=[1,2,3,4,5,6,7]
print(list[0:6])
print(list[:])

s={(1,2,33,444,6,"hi python")}
print(s)

a=10        # bitwise operators
   b=4
   print(a & b)
   print(a | b)
   print(~a)
   print(a ^ b)
   print(a >> 2)
   print(a << 2)
   print(~b)
   print(a == b)
   print(a >> 1)
   print(a >> 2)
   print(a >> 3)
   print(a<<2)
   print(a<<3)
   print(a<<4)
   print(a>b)
   print(a>=b)
   print(a<=b)

a=100
b=50
c=2.0
d=-10
print(a+b*c-d)
print((a*b)+(c*d))
print(a*(c+d)*d)

a=9
b=12
c=3
x=a-b/3+c*2-1
print(x)
y=b/(3+c)*(2-1)
print(y)
z=a-(b/(3+c)*2)
print(z)

days=int(input("Enter no of days "))
years=(days//365)
months=(days%365)//30
day=(days%365)%30
print('Years : ',years,'\n Months : ',months,'\n Days : ',day)

seconds=float(input("Enter number of seconds "))
hours=(seconds//3600)
minutes=(seconds%3600)//60
second=(seconds%3600)%60
milisecond=((seconds%3600)%60)*100
print(  ' Hours%.2f'%hours,'\n Minutes',minutes,'\n Seconds',second,'\n','milisecond', milisecond)

notes=int(input("Enter amount of money")) #This is step by step it gors extended (we are breaking one big digit into different values or notes )
rupee100=notes//100
rupee50=(notes%100)//50
rupee20=((notes%100)%50)//20
rupee10=(((notes%100)%50)%20)//10
rupee5=((((notes%100)%50)%20)%10)//5
rupee2=(((((notes%100)%50)%20)%10)%5)//2
rupee1=((((((notes%100)%50)%20)%10)%5)%2)//1
print('Rs 100\-',rupee100)
print(rupee50)
print(rupee20)
print(rupee10)
print(rupee2)
print(rupee1)

x=int(input("Enetr distance between two cities (in km) "))
m=x*1000
cm=x*100000
ft=x*3280.40
inch=x*39370.1
print("Distance between to cities is ",m,'km')
print("Distance between to cities is ",cm,'cm')
print("Distance between to cities is ",ft,'ft')
print("Distance between to cities is ",inch,'inch')

a=100
b=2
c=25
d=4
result1=a*b+c*d
print(result1)

Val=False
if Val==True:
 print("Value is True")
print("Value is False")

a=10
if a==12:
 print("Value of a is 10")
print("Value of a not 10")

a=int(input("Enter the first value"))
b=int(input("Enter the second value"))

if b>a:
  print(" b is greater than a")
else:
  print("b is smaller than a")
# In front of print that white Space Tellus us that is works like curly braces which is user in that..

x=int(input("Enter the marks of SVC: "))
y=int(input("Enter the marks of EP: "))
z=int(input("Enter the marks of PP: "))
u=int(input("Enter the marks of UHV: "))
s=int(input("Enter the marks of EE: "))
sum=x+y+z+u+s
percentage=(sum/500)*100
print("Total percentage is :",percentage)
if percentage>=35:
  print("Student is pass")
else:
  print("Student is fail")  
  # Here we have used if the student is pass in exam or not by using if else....

x=int(input("Enter the value of a "))
x=a+1,a+3,a+5,a+7
y=a,a+2,a+4,a+6,a+8
print("The numbers are ",x)
print("The even numbers are ",y)

a=int(input("Enter the number "))
if (a%2):
  print("The number is odd")
else:
  print("The number is even")  
  #Here we have find that the number is even or the number is odd

a=int(input("Number of class Attended by the Student of PP (out of 50) "))
b=int(input("Number of class Attended by the Student of BCME (out of 50) "))
c=int(input("Number of class Attended by the Student of EP (out of 50) "))
d=int(input("Number of class Attended by the Student of SVC (out of 50) "))
e=int(input("Number of class Attended by the Student of EE (out of 50) "))
sum=a+b+c+d+e
per=(sum/250)*100
print("Candidate has attend the class  (percentage)",per)
if per>=75:
  print("Candidate can able to sit foe exam")
else:
  print("Candidate cannot able to sit for exam")   
  #Here we have used how the student has attended the class in percentage and is  he able to sit foe examor not

#To check th enumber is positive or negative
u=int(input("Enter the value "))
if u<0:
  print("The number is Negative")
else:
  print("The number is Positive")

#To check the number i even or odd
a=int(input("Enter the number "))
if a%2:
  print("The number is odd ")
else:
  print("The number is even")

#To check wich number is greater and which is smaller
a=int(input("Enter the first value "))
b=int(input("Enter the second value "))
if a>b:
  print("The Maximum number is :-",a,'\n',"The Minimumnumber is :-",b)

if a<b:
  print("The Maximum number is :-",b,'\n',"The Minimum number is :-",a)

if a==b:
  print("Both are Equals")

# to check the number is divisible by 5 or not
a=int(input("Enter the number "))
if a%5==0:
  print("The number is Divisible by 5")
else:
  print("The number is not divisible by 5")

a=int(input("Enter the Number :-"))
if (a%5==0) and (a%7==0):
  print("The number is divisible by 5 and 7 ")
else:
  print("The number is not divisible by 5 and 7 ")

a=("Enter the amount of sugar (40rs / kg)")
a=int(input(a))
b=("Enter the amount of rice (70 rs/kg)")
b=int(input(b))
c=("Enter the amount of tur dal (100 rs /kg )")
c=int(input(c))
x=(a*40)+(b*70)+(c*100)
x=print("The total amount is ",x)

#Python program to find the greatest of three numbers using If-else statement
num1=int(input("Enter the first number"))
num2=int(input("Enter the second number"))
num3=int(input("Enter the third number"))
if (num1>num2) and (num1>num3):
  greatestNumber=num1
  print("The greatest number is ",num1)

elif (num2>num1) and (num2>num3):
  greatestNumber=num2
  print("The greatest number is ",num2)

elif (num3>num1) and (num3>num2):
  greatestNumber=num3
  print("The greatest number is ",num3)

else:
  print("All are same")